### ISSUE TITLE
How to stop this extension overrides every new tab created with a mindmap_tab?

### ISSUE THREAD

**Issue by spambotalotalot** [yoichiro/mindmap_tab#14]
I am using the ext to map my google doc/sheets etc and love the experience - But I also using extension "New Tab Website offered by Federico Elles" which creates new tabs that open with a selectable default (in my case Google.co.uk) - Your extension overrides this extsion and every new tab now is a mindmap_tab - Any thoughts how to ensure all my new tabs do not inserting the mindmap_tab every time?

**Comment by yoichiro** [comment]
Since 2.7.0, the overriding a default new tab was abolished.
