### ISSUE TITLE
How do I open the mindmap tab? when I click "mindmap tab" it opens the chrome extension page..

### ISSUE THREAD

**Issue by tomer-ben-david** [yoichiro/mindmap_tab#28]

**Comment by tomer-ben-david** [comment]
oh now i see its the default on new tab. isn't it possible to open it from the context menu? i mean fromthe mindmapsmall icon?

**Comment by yoichiro** [comment]
Since 2.7.0, you can open the new tab provided by this extension with clicking the browser action.
