### ISSUE TITLE
'Copy' doesnt work for me, at all

### ISSUE THREAD

**Issue by dizman99** [yoichiro/mindmap_tab#37]
Hello!

I'm using this MM for a while now and am pleased with the progress it takes over the months.
However, I was not able to use the "copy" feature from the start. Export works fine, but s.t. I just want to have the textual tree in an editor. All three options under copy do not transport the info to the clipboard and from there to an editor. I was shown whatever I had in there before using copy->as markup for instance.
Using Chrome and Windows 7 64 bit. No other clipboard tools or similar.
Thanks in advance.

**Comment by yoichiro** [comment]
@dizman99 Thank you for the reporting. From Chrome 65, both Copy and Export features don't work. I will release a new version to fix them.

**Comment by yoichiro** [comment]
This issue will be fixed at #40

**Comment by dizman99** [comment]
Hello!

Thank you very much! It all works like a breeze now! Really nice! :)

regards,

Dietmar

2018-03-28 4:54 GMT+02:00 Yoichiro Tanaka <notifications@github.com>:
