### ISSUE TITLE
When the user clicks on the icon , mindmap editor opens in the dedicated page to mindmap.

### ISSUE THREAD

**Issue by y-sama** [yoichiro/mindmap_tab#6]
As　of [LiveMD](http://www.moongift.jp/2014/08/livemd-google-chrome%E6%A9%9F%E8%83%BD%E6%8B%A1%E5%BC%B5%E3%81%AEmarkdown%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BF/).
I want to select that editor open in the start page of chrome, or the dedicated page to mindmap.

**Comment by yoichiro** [comment]
Currently, I don't intend to agree your opinion, because I think this new tab replacement is convenient to me.

**Comment by yoichiro** [comment]
Since 2.7.0, you can open this extension's tab by clicking a browser action. Instead, the overriding a new tab was abolished.
